### ISSUE TITLE
Is it possible to resolve memory leak in retracing?

### ISSUE THREAD

**Issue by lovewsy** [ARM-software/patrace#35]
If I repaly a pat multiple times, the memory usage is increasingly rising. Does it possible to correctly release the memory allocated by retracing?

**Comment by per-mathisen-arm** [comment]
That should not be happening. Even if the replayer leaked memory, all that memory should be reclaimed by the OS once it exits. How are you playing it multiple times?

**Comment by lovewsy** [comment]
I appologize for unclear description. 

First I replay a pat on linux platform. I called gRetracer.Retrace function in "retrace_main.cpp" multiple times. What I found is that the memory used by gRetracer seems not be released. I can not find a way to properly replay a pat multiple times in one execution of the paretrace.

**Comment by per-mathisen-arm** [comment]
Yes, that is a use case we haven't really tried, so I would expect there to be issues. What are you trying to accomplish?

**Comment by lovewsy** [comment]
I try to implement some automatical optimization about draw call time. I need to replace some rendering resource of pat, such as shader or mesh. And then retrace multiple times to get the performance and quality result of our optimization.

**Comment by per-mathisen-arm** [comment]
Why not just run paretrace multiple times? That is what we do.

As for memory issue, make sure you do not try to use preload on a too large frame range. That is usually when we hit issues.

**Comment by lovewsy** [comment]
Yes, I also implement multi-process mode for multiple retracing. But sometimes, the memory usage is still high in one retrace on Android platform. Is there a proper way to reduce the memory usage in one retrace? Also, we haven't used the preload option. What does preload option work for?

**Comment by per-mathisen-arm** [comment]
Preload loads the entire specified framerange into memory so that your runs are not impacted by the latency of loading data from disk. We haven't really had problems with running out of memory unless we use too large frameranges with preload. One thing you could try is to run the clientsidetrim tool to see if there are many resources kept around for too long - it will inject extra delete calls to free up memory earlier. You can try to use the fastforward tool to trim away the first parts of a trace, but this is not likely to reduce memory usage as it just removes draw calls.
